# Generated by Django 3.1.7 on 2021-03-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_bookmark_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='DATETIME'),
        ),
    ]
