# Generated by Django 3.1.7 on 2021-03-25 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_auto_20210325_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='DATETIME'),
        ),
    ]
